_BASE_: "./Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOV7"
  WEIGHTS: ""
  MASK_ON: False
  BACKBONE:
    NAME: "build_res2net_backbone"
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RESNETS:
    R2TYPE: "res2net50_v1b"
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"] # fpn produce 4 levels, only using 3 for now
  YOLO:
    # ANCHORS:
    #   [
    #     [[116, 90], [156, 198], [373, 326]],
    #     [[30, 61], [62, 45], [42, 119]],
    #     [[10, 13], [16, 30], [33, 23]],
    #   ]
    # EDIT: Computed on MTSD with compute_anchors_main.py
    ANCHORS:
      [
        [[42, 39], [65, 70], [128, 138]], 
        [[18, 16], [27, 25], [20, 50]], 
        [[7, 8], [12, 11], [10, 24]],
      ]
    CLASSES: 80  # EDIT: Automatically changed in argparse.py
    IN_FEATURES: ["res3", "res4", "res5"] # p3, p4, p5 from FPN
    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.7
    IGNORE_THRESHOLD: 0.5
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
    WIDTH_MUL: 1.0
    LOSS:
      LAMBDA_IOU: 1.0
    NECK:
      TYPE: "fpn"
      WITH_SPP: true

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

INPUT:
  MIN_SIZE_TRAIN: (2048,)
  MAX_SIZE_TRAIN: 2048
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TEST: 2048
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: False
  # MOSAIC:
  #   ENABLED: True
  #   NUM_IMAGES: 4
  #   DEBUG_VIS: True
  #   # MOSAIC_WIDTH: 960
  #   # MOSAIC_HEIGHT: 540
  MOSAIC_AND_MIXUP:  # TODO(feature): mosaic is not implemented yet
    ENABLED: False
    DEBUG_VIS: False
    ENABLE_MIXUP: True
    DISABLE_AT_ITER: 40000

SOLVER:
  AMP:
    ENABLED: False
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (50000, 70000, 75000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 1500
  MAX_ITER: 80000
  LR_SCHEDULER_NAME: "WarmupCosineLR"

TEST:
  EVAL_PERIOD: 5000

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 1