_BASE_: "Base-YOLOF.yaml"
SEED: 0   # EDIT
CUDNN_BENCHMARK: True   # EDIT
MODEL:
  WEIGHTS: "./pretrained_models/YOLOF_CSP_D_53_DC5_9x.pth"
  # or
  # WEIGHTS: "./output/yolof/CSP_D_53_DC5_9x/model_final.pth"
  META_ARCHITECTURE: "YOLOF"
  MASK_ON: False
  BACKBONE:
    NAME: "build_darknet_backbone"
  DARKNET:
    NORM: "SyncBN"
    RES5_DILATION: 2
  ANCHOR_GENERATOR:
    SIZES: [[16, 32, 64, 128, 256, 512]]
  YOLOF:
    ENCODER:
      IN_CHANNELS: 1024
      NUM_RESIDUAL_BLOCKS: 8
      BLOCK_DILATIONS: [1, 2, 3, 4, 5, 6, 7, 8]
      NORM: "SyncBN"
      ACTIVATION: "LeakyReLU"
    DECODER:
      NUM_ANCHORS: 6
      NORM: "SyncBN"
      ACTIVATION: "LeakyReLU"
    POS_IGNORE_THRESHOLD: 0.1
    NEG_IGNORE_THRESHOLD: 0.8
    BOX_TRANSFORM:
      ADD_CTR_CLAMP: True
      CTR_CLAMP: 16
SOLVER:
  BASE_LR: 0.01  # Original: 0.02
  BACKBONE_MULTIPLIER: 1.0
  STEPS: (52500, 62500)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 5000
INPUT:
  JITTER_CROP:
    # ENABLED: True
    ENABLED: False
  RESIZE:
    # ENABLED: True
    ENABLED: False
  DISTORTION:
    # ENABLED: True
    ENABLED: False
  MOSAIC:
    # ENABLED: True
    ENABLED: False
  RANDOM_FLIP: 'none'  # EDIT: traffic sign can be flipped?. Option: 'none' (orig), 'horizontal' (shape)
  # EDIT: follow MTSD paper: no resizing during training but crop to (1000, 1000)
  # TODO: does setting to 0 disables resizing? 
  # If not working, see https://github.com/facebookresearch/detectron2/issues/2275
  MIN_SIZE_TRAIN: (2048, )
  MAX_SIZE_TRAIN: 2048  # Original training is 5000
  # Only used during traning
  CROP:
    ENABLED: False
    TYPE: 'absolute'
    SIZE: (1000, 1000)
  # EDIT: Test with max size 2048 or 4000. This is slightly different from 
  # MTSD paper where images smaller than 2048 are not saled up.
  # Size of the smallest side of the image during testing. Set to zero to 
  # disable resize in testing.
  MIN_SIZE_TEST: 2048  # This will be set by args during testing
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 2048  # This will be set by args during testing
DATALOADER:
  NUM_WORKERS: 24
  SAMPLER_TRAIN: 'RepeatFactorTrainingSampler'  # EDIT: default: 'TrainingSampler'
  REPEAT_THRESHOLD: 1.0  # EDIT: default: 0
DATASETS:
  TRAIN: ('mtsd_no_color_train', )  # EDIT
  TEST: ('mtsd_no_color_val', )  # EDIT
OUTPUT_DIR: "output/yolof/CSP_D_53_DC5_3x"
