# See defaults at https://github.com/chensnathan/YOLOF/blob/master/yolof/config/defaults.py
_BASE_: "Base-YOLOF.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  YOLOF:
    BOX_TRANSFORM:
      ADD_CTR_CLAMP: True
      CTR_CLAMP: 16
# SOLVER:
#   IMS_PER_BATCH: 64
#   BASE_LR: 0.12
#   WARMUP_FACTOR: 0.00066667
#   WARMUP_ITERS: 1500
#   STEPS: (15000, 20000)
#   MAX_ITER: 22500
#   CHECKPOINT_PERIOD: 2500
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_NORM: 0.0
  MOMENTUM: 0.9
  BACKBONE_LR_FACTOR: 0.334
  STEPS: (52500, 62500)
  MAX_ITER: 80000
  CHECKPOINT_PERIOD: 5000
INPUT:
  JITTER_CROP:
    # ENABLED: True
    ENABLED: False
  RESIZE:
    # ENABLED: True
    ENABLED: False
  DISTORTION:
    # ENABLED: True
    ENABLED: False
  MOSAIC:
    # ENABLED: True
    ENABLED: False
  RANDOM_FLIP: 'none'  # EDIT: traffic sign can be flipped?. Option: 'none' (orig), 'horizontal' (shape)
  # EDIT: follow MTSD paper: no resizing during training but crop to (1000, 1000)
  # TODO: does setting to 0 disables resizing? 
  # If not working, see https://github.com/facebookresearch/detectron2/issues/2275
  MIN_SIZE_TRAIN: (2048, )
  MAX_SIZE_TRAIN: 2048  # Original training is 5000
  # Only used during traning
  CROP:
    ENABLED: False
    TYPE: 'absolute'
    SIZE: (1000, 1000)
  # EDIT: Test with max size 2048 or 4000. This is slightly different from 
  # MTSD paper where images smaller than 2048 are not saled up.
  # Size of the smallest side of the image during testing. Set to zero to 
  # disable resize in testing.
  MIN_SIZE_TEST: 2048  # This will be set by args during testing
  # Maximum size of the side of the image during testing
  MAX_SIZE_TEST: 2048  # This will be set by args during testing
DATALOADER:
  NUM_WORKERS: 24
  SAMPLER_TRAIN: 'RepeatFactorTrainingSampler'  # EDIT: default: 'TrainingSampler'
  REPEAT_THRESHOLD: 1.0  # EDIT: default: 0
DATASETS:
  TRAIN: ('mtsd_no_color_train', )  # EDIT
  TEST: ('mtsd_no_color_val', )  # EDIT
OUTPUT_DIR: "output/yolof/R_50_C5_1x"


# LR_SCHEDULER=dict(
#     STEPS=(15000, 20000),
#     MAX_ITER=22500,
#     WARMUP_FACTOR=0.00066667,
#     WARMUP_ITERS=1500
# ),
# OPTIMIZER=dict(
#     NAME="D2SGD",
#     BASE_LR=0.12,
#     BIAS_LR_FACTOR=1.0,
#     WEIGHT_DECAY=0.0001,
#     WEIGHT_DECAY_NORM=0.0,
#     MOMENTUM=0.9,
#     BACKBONE_LR_FACTOR=0.334
# ),
# IMS_PER_BATCH=64,
# IMS_PER_DEVICE=8,